### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by nyukers** [IamCreateAI/Ruyi-Models#10]
Hi all,
can I use it with 11Gb VRAM ?

**Comment by cellzero** [comment]
Yes, we offer GPU memory optimization options (`GPU_memory_mode` and `GPU_offload_steps`), and 11GB of VRAM can generate videos at various resolutions and frame rates.

We recommend trying to enable `low_gpu_mode`, as this can effectively improve the resolution and frame rate of the videos. However, please note that enabling `low_gpu_mode` will significantly increase the generation time.

For more detailed information, please refer to the [GPU memory optimization section](https://github.com/IamCreateAI/Ruyi-Models#gpu-memory-optimization) in README.md.

**Comment by nyukers** [comment]
**Win10, 32Gb RAM, 11Gb VRAM**
What am I doing wrong?

[2024-12-19 20:59:40.228] !!! Exception during processing !!! Allocation on device 
[2024-12-19 20:59:40.229] Traceback (most recent call last):
  File "d:\SDComfyUI\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "d:\SDComfyUI\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "d:\SDComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "d:\SDComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\comfyui\comfyui_nodes.py", line 385, in process
    sample = pipeline(
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\pipeline\pipeline_ruyi_inpaint.py", line 984, in __call__
    noise_pred = self.transformer(
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\models\transformer3d.py", line 1147, in forward
    hidden_states = block(
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\models\attention.py", line 1595, in forward
    attn_output = self.attn1(
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\diffusers\models\attention_processor.py", line 495, in forward
    return self.processor(
  File "d:\SDComfyUI\python_embeded\lib\site-packages\diffusers\models\attention_processor.py", line 2612, in __call__
    hidden_states = F.scaled_dot_product_attention(
torch.OutOfMemoryError: Allocation on device

**Comment by cellzero** [comment]
It seems that the issue may be caused by insufficient GPU memory. Essentially, generating videos with **higher resolutions or more frames requires more GPU memory**. According to my tests, using **low memory mode and 0 steps** to generate a video at **512 resolution with 120 frames requires over 11 GiB of GPU memory**.

You might first try generating a video with **fewer frames** (for example, 72 frames, which is about 3 seconds) or at a **lower resolution** (the minimum supported is 384 resolution).

- If that works smoothly, it indicates that the runtime environment is functioning properly. Next, you can try combining low memory mode with 10, 7, 5, or 1 steps (yes, these two options can work simultaneously in ComfyUI) to generate videos with higher resolutions and more frames. I will also test the specific GPU memory usage and execution time for these combinations over the weekend, and I expect to have complete results by next Monday (December 23) to update on GitHub.

- If lowering the resolution and frame rate still doesn't resolve the issue, it is likely that other problems have arisen. In this case, please feel free to reach out for assistance. Providing the complete error message would greatly help us quickly identify the problem, and I will do my best to offer support and solutions.

**Comment by nyukers** [comment]
Total VRAM 11264 MB, total RAM 32613 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : cudaMallocAsync
Using xformers attention
![unnamed](https://github.com/user-attachments/assets/059ecff9-bf9d-4a11-81c9-e74fa11689e3)

got prompt
Loading pipeline components...: 0it [00:00, ?it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [16:45<00:00, 40.22s/it]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "d:\SDComfyUI\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "d:\SDComfyUI\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "d:\SDComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "d:\SDComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\comfyui\comfyui_nodes.py", line 385, in process
    sample = pipeline(
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\pipeline\pipeline_ruyi_inpaint.py", line 1055, in __call__
    video = self.decode_latents(latents)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\pipeline\pipeline_ruyi_inpaint.py", line 518, in decode_latents
    video = self.vae.decode(latents)[0]
  File "d:\SDComfyUI\python_embeded\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\models\autoencoder_magvit.py", line 340, in decode
    decoded = self._decode(z).sample
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\models\autoencoder_magvit.py", line 311, in _decode
    dec = self.decoder(z)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\vae\ldm\models\omnigen_enc_dec.py", line 552, in forward
    next_frames = self.single_forward(x[:, :, i: i + self.mini_batch_decoder, :, :], previous_features, after_features)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\vae\ldm\models\omnigen_enc_dec.py", line 499, in single_forward
    x = up_block(x)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\vae\ldm\modules\vaemodules\up_blocks.py", line 387, in forward
    x = conv(x)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\vae\ldm\modules\vaemodules\common.py", line 239, in forward
    x = self.conv1(x)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\Ruyi-Models\ruyi\vae\ldm\modules\vaemodules\common.py", line 108, in forward
    return super().forward(x)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "d:\SDComfyUI\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 720, in _conv_forward
    return F.conv3d(
torch.OutOfMemoryError: Allocation on device

**Comment by cellzero** [comment]
I'm sorry to see this situation.

I suspect that the out-of-memory issue is due to the data type. Since the 1080 Ti does not support bfloat16, it is likely that float32 is being used during execution, which would double the memory requirements and ultimately lead to the out-of-memory problem. However, the **current model only supports running in bfloat16** (float16 seems to trigger precision overflow, making it impossible to generate videos correctly), so a **GPU that supports bfloat16 is needed**.

At the moment, I haven't found a solution to this issue. Perhaps all I can do is add a note in the README stating that 'a GPU that supports bfloat16 is required'.

If anyone has any suggestions or solutions, please feel free to reach out to me.

**Comment by nyukers** [comment]
I would be grateful if you could tell me a few NVIDIA card models with 16GB VRAM that will definitely work with your video-generator. Thank you.

**Comment by cellzero** [comment]
We have tested the model on both the RTX 3090 and RTX 4090, and it runs smoothly on both. According to online information, [NVIDIA's Ampere architecture and later versions support BF16](https://forums.developer.nvidia.com/t/quadro-rtx-6000-does-not-handle-bf16-please-make-an-update/312545/8), so I believe that using either the 30 series or 40 series GPUs should work well with this model.

**Comment by cellzero** [comment]
I came across this [GPU buying guide](https://comfyui-wiki.com/en/install/install-comfyui/gpu-buying-guide), which lists various GPUs along with their supported data types, prices, performance metrics, and more. I hope it will be helpful.
