### ISSUE TITLE
Torch ROCm - RuntimeError: Unsupported memory format for group normalization: ChannelsLast3d

### ISSUE THREAD

**Issue by imba-pericia** [IamCreateAI/Ruyi-Models#6]
ROCm - RuntimeError: Unsupported memory format for group normalization: ChannelsLast3d

pytorch version: 2.6.0.dev20241113+rocm6.2

```
got prompt
!!! Exception during processing !!! Unsupported memory format for group normalization: ChannelsLast3d
Traceback (most recent call last):
  File "/home/qwer/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/qwer/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/qwer/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/qwer/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/qwer/ComfyUI/custom_nodes/Ruyi-Models/comfyui/comfyui_nodes.py", line 385, in process
    sample = pipeline(
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/qwer/ComfyUI/custom_nodes/Ruyi-Models/ruyi/pipeline/pipeline_ruyi_inpaint.py", line 845, in __call__
    mask_latents, masked_video_latents = self.prepare_mask_latents(
  File "/home/qwer/ComfyUI/custom_nodes/Ruyi-Models/ruyi/pipeline/pipeline_ruyi_inpaint.py", line 375, in prepare_mask_latents
    mask_bs = self.vae.encode(mask_bs)[0]
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/home/qwer/ComfyUI/custom_nodes/Ruyi-Models/ruyi/models/autoencoder_magvit.py", line 280, in encode
    x = self.tiled_encode(x, return_dict=return_dict)
  File "/home/qwer/ComfyUI/custom_nodes/Ruyi-Models/ruyi/models/autoencoder_magvit.py", line 384, in tiled_encode
    tile = self.encoder(tile)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qwer/ComfyUI/custom_nodes/Ruyi-Models/ruyi/vae/ldm/models/omnigen_enc_dec.py", line 272, in forward
    next_frames = self.single_forward(x[:, :, i: i + self.mini_batch_encoder, :, :], None, None)
  File "/home/qwer/ComfyUI/custom_nodes/Ruyi-Models/ruyi/vae/ldm/models/omnigen_enc_dec.py", line 215, in single_forward
    x = self.mid_block(x)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qwer/ComfyUI/custom_nodes/Ruyi-Models/ruyi/vae/ldm/modules/vaemodules/mid_blocks.py", line 194, in forward
    hidden_states = resnet(hidden_states)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qwer/ComfyUI/custom_nodes/Ruyi-Models/ruyi/vae/ldm/modules/vaemodules/common.py", line 236, in forward
    x = self.norm1(x)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 313, in forward
    return F.group_norm(input, self.num_groups, self.weight, self.bias, self.eps)
  File "/home/qwer/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2965, in group_norm
    return torch.group_norm(
RuntimeError: Unsupported memory format for group normalization: ChannelsLast3d

Prompt executed in 36.15 seconds
```

**Comment by cellzero** [comment]
I haven't encountered a similar situation, but I suspect it may be related to the PyTorch preview version. I was able to use version 2.5.1 without any issues, so installing that version might be helpful. 

[This issue](https://github.com/kijai/ComfyUI-CogVideoXWrapper/issues/306) describes a similar problem, and I hope you find it useful.

**Comment by imba-pericia** [comment]
> I haven't encountered a similar situation, but I suspect it may be related to the PyTorch preview version. I was able to use version 2.5.1 without any issues, so installing that version might be helpful.
> 
> [This issue](https://github.com/kijai/ComfyUI-CogVideoXWrapper/issues/306) describes a similar problem, and I hope you find it useful.

Thx.
